# Generated by Django 4.0.5 on 2022-06-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spm', '0003_customuser_delete_choice_delete_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
