# Generated by Django 4.0.5 on 2022-06-16 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spm', '0004_alter_user_options_user_date_joined_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='some',
        ),
    ]
