# Generated by Django 4.0.5 on 2022-06-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spm', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='spm',
        ),
    ]
