# Generated by Django 4.0.5 on 2022-06-16 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spm', '0005_remove_user_some'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crewid',
            field=models.CharField(default=django.utils.timezone.now, max_length=7, unique=True),
            preserve_default=False,
        ),
    ]
