# Generated by Django 4.0.5 on 2022-06-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spm', '0006_user_crewid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='crewid',
            field=models.CharField(max_length=7),
        ),
    ]
