# Generated by Django 4.0.5 on 2022-06-16 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spm', '0007_alter_user_crewid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='station',
            field=models.CharField(default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='crewid',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=150),
        ),
    ]
