# Generated by Django 4.0.5 on 2022-06-16 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spm', '0008_user_station_alter_user_crewid_alter_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='empid',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
    ]
