# Generated by Django 4.0.5 on 2022-06-16 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spm', '0009_user_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='appointment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
