# Generated by Django 4.0.5 on 2022-06-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spm', '0010_user_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='crewid',
            new_name='crew_ID',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='empid',
            new_name='emp_ID',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
